### ISSUE TITLE
Alpha / Transparency and Import Handling

### ISSUE THREAD

**Issue by throttlekitty** [GameTechDev/Intel-Texture-Works-Plugin#4]
In the interest of modding games, auto-applying the alpha channel as transparency is a hindrance. Particularly when alpha isn't transparency, such as a diffuse map packed with parallax, or many types of effect textures.

I'd like to request an import settings option, since there are cases where this behavior is desired. (and also to suppress the mipmap question on import too? It's rare as a user that I need to load them.)

[I don't think we can add labels to issues. Yeah, we don't have permissions for that, even after posting an issue.]

**Comment by jonwd7** [comment]
Hi @throttlekitty :)

I know we talked about this in chat back then, but I just noticed this post: https://software.intel.com/en-us/forums/developing-games-and-graphics-on-intel/topic/604618

Where someone calls this a "flaw".  They don't seem to know that they can restore the color by using:

Layer > Layer Mask > From Transparency

To use the file from their example, here is what it looks like after using From Transparency and then disabling the Layer Mask:

![untitled-1](https://cloud.githubusercontent.com/assets/170077/11920670/c222b386-a743-11e5-8133-333b65f9a046.png)

So just for anyone coming to this ticket from that page, here is a solution for you.

**Comment by throttlekitty** [comment]
Wow. That works, but makes no sense to me, thanks! (I must've forgotten this conversation)

**Comment by jawilli312** [comment]
Thank you jonwd7. We will have an alpha handling option in the next release.

**Comment by ParasiteX** [comment]
A trick to i found to separate the transparency into an Alpha Channel. Is to go to the menu Layers -> Layer Mask -> From Transperacy.
You should then get a "Layer 0 Mask" channel. Duplicate this channel and name it "Alpha 1".
Then delete the "Layer 0 Mask" channel. And it will remove the transparency completely, revealing whatever was hidden behind the transparency. And give you a separate alpha channel.
You should also after that convert "Layer 0" into a background layer. So that ITW can properly save it as color + alpha later.
Otherwise, make sure to untick layers, when trying to save as color + alpha.

**Comment by ParasiteX** [comment]
I uploaded a Photoshop action i made, that separates the alpha channel and removes transparency.
https://www.dropbox.com/s/4uh6nb1esluxf32/Useful%20Actions.atn?dl=0

**Comment by jawilli312** [comment]
Thanks ParasiteX!

The next plugin release will provide alpha handling options on load.

**Comment by rymdkakor** [comment]
Hello!

I'm using the plugin in our student game project and we might have noticed a problem, but it just might be that we're using the plugin for things it was not intended for.

I devised a texture packing pipeline that is as follows:

1 normal map texture
1 Albedo texture with transparency in the alpha channel.
1 "AOREM"-texture with the Ambient Occlusion map in the alpha channel, the Roughness map in the green channel, an Emissive mask in the red channel and a Metalness mask in the blue channel.

The problem we are having is that the plugin doesn't seem to save out the alpha channel at all, even in the 1.04 release. Thus our textures lack transparency and gets a completely black AO, since our engine is looking for the non-existent alpha channel.

Our deadline is next Wednesday, please help!

Dag Lindwall, Game Art student at The Game Assembly.

**Comment by oomek** [comment]
There should be a setting somewhere to allow to load transparency as an alpha channel by default without the dialog box. It would be very useful when opening many textures at once.
